language: node_js

node_js:
  - "8"

stages:
  - test
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: deploy
      script: skip
      deploy:
        provider: bluemixcloudfoundry
        skip_cleanup: true
        manifest: manifest.yml
        username: $BLUEMIX_USER
        password: $BLUEMIX_APIKEY
        organization: $BLUEMIX_ORGANIZATION
        space: $BLUEMIX_SPACE
