language: node_js
cache:
  directories:
  - node_modules
  yarn: true

node_js:
  - "8"

jobs:
  include:
    - stage: test
    - script:
      - yarn test
    - stage: deploy
    - deploy:
        provider: bluemixcloudfoundry
        skip_cleanup: true
        manifest: manifest.yml
        username: $BLUEMIX_USER
        password: $BLUEMIX_APIKEY
        organization: $BLUEMIX_ORGANIZATION
        space: $BLUEMIX_SPACE
